name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
      - name: Lint
        run: bundle exec rake rubocop
  
  report:
    name: Allure report
    runs-on: ubuntu-20.04
    if: always()
    steps:
      - name: Download allure-results
        uses: actions/download-artifact@v3
        with:
          name: allure-results
